//! OpenCode installer.
//!
//! Three artifacts:
//!   1. `AGENTS.md` — marker-scoped capability block (static fallback).
//!   2. `.opencode/plugins/sigil.js` — a `tool.execute.before` plugin
//!      that echoes the sigil hint when bash-like tools fire.
//!   3. `opencode.json` — registers `plugins/sigil.js` under the
//!      `plugins` array so OpenCode loads it on startup.
//!
//! The plugin is a tiny CommonJS module — no dependencies, minimal
//! surface. Uninstall removes the file and its registration entry, and
//! deletes `opencode.json` if nothing else of sigil's remains and the
//! rest of the file is already empty.

use std::path::Path;

use anyhow::{Context as _, Result};
use serde_json::{json, Value};

use super::{capability_block, remove_marker_block, upsert_marker_block, UpsertResult};

const PLUGIN_REL: &str = ".opencode/plugins/sigil.js";
const HOOK_ID: &str = "sigil-plugin";
const HINT_LINE: &str = "sigil in this repo — for structural questions reach for sigil FIRST: `sigil where X` (find definition), `sigil context X` (full bundle), `sigil callers/callees X`, `sigil symbols F --depth 1`. Empty result prints `Did you mean?` on stderr — retry with suggestion before grep.";

pub fn install(root: &Path) -> Result<Vec<InstallStep>> {
    let mut steps = Vec::new();

    let agents_md = root.join("AGENTS.md");
    steps.push(InstallStep::AgentsMd(
        upsert_marker_block(&agents_md, &capability_block())
            .with_context(|| format!("upsert {}", agents_md.display()))?,
    ));

    let plugin_path = root.join(PLUGIN_REL);
    if let Some(p) = plugin_path.parent() {
        std::fs::create_dir_all(p)?;
    }
    let plugin_source = plugin_js();
    let plugin_result = if plugin_path.exists()
        && std::fs::read_to_string(&plugin_path).ok().as_deref() == Some(plugin_source.as_str())
    {
        UpsertResult::Unchanged
    } else {
        std::fs::write(&plugin_path, &plugin_source)?;
        if plugin_path.exists() {
            UpsertResult::Updated
        } else {
            UpsertResult::Created
        }
    };
    steps.push(InstallStep::Plugin(plugin_result));

    let opencode_json = root.join("opencode.json");
    let changed = upsert_plugin_registration(&opencode_json)?;
    steps.push(InstallStep::OpencodeJson(if changed {
        UpsertResult::Updated
    } else {
        UpsertResult::Unchanged
    }));

    Ok(steps)
}

pub fn uninstall(root: &Path) -> Result<Vec<UninstallStep>> {
    let mut steps = Vec::new();
    let agents_md = root.join("AGENTS.md");
    steps.push(UninstallStep::AgentsMd(remove_marker_block(&agents_md)?));

    let plugin_path = root.join(PLUGIN_REL);
    let plugin_removed = if plugin_path.exists() {
        std::fs::remove_file(&plugin_path)?;
        if let Some(parent) = plugin_path.parent()
            && parent.read_dir().map(|mut d| d.next().is_none()).unwrap_or(false)
        {
            let _ = std::fs::remove_dir(parent);
        }
        true
    } else {
        false
    };
    steps.push(UninstallStep::Plugin(plugin_removed));

    let opencode_json = root.join("opencode.json");
    steps.push(UninstallStep::OpencodeJson(remove_plugin_registration(
        &opencode_json,
    )?));

    Ok(steps)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InstallStep {
    AgentsMd(UpsertResult),
    Plugin(UpsertResult),
    OpencodeJson(UpsertResult),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UninstallStep {
    AgentsMd(bool),
    Plugin(bool),
    OpencodeJson(bool),
}

fn plugin_js() -> String {
    // Minimal CommonJS plugin conforming to OpenCode's plugin contract.
    // The hook fires before tool execution and returns context text that
    // OpenCode appends to the model's next turn.
    format!(
        r#"// sigil plugin — {HOOK_ID}
// Generated by `sigil opencode install`. Safe to remove; regenerated on reinstall.

module.exports = {{
  name: "sigil",
  "tool.execute.before": async (ctx) => {{
    // Fire only for bash-like tools where a grep/ls is about to happen.
    const name = (ctx && ctx.tool && ctx.tool.name) || "";
    if (!/bash|shell/i.test(name)) return;
    return {{
      context: {hint_json},
    }};
  }},
}};
"#,
        HOOK_ID = HOOK_ID,
        hint_json = serde_json::to_string(HINT_LINE).unwrap(),
    )
}

fn upsert_plugin_registration(path: &Path) -> Result<bool> {
    let mut cfg: Value = if path.exists() {
        let text = std::fs::read_to_string(path)?;
        if text.trim().is_empty() {
            json!({})
        } else {
            serde_json::from_str(&text)?
        }
    } else {
        json!({})
    };

    let obj = cfg
        .as_object_mut()
        .ok_or_else(|| anyhow::anyhow!("opencode.json root must be an object"))?;
    let plugins = obj.entry("plugins".to_string()).or_insert_with(|| json!([]));
    let arr = plugins
        .as_array_mut()
        .ok_or_else(|| anyhow::anyhow!("plugins must be an array"))?;
    let entry = PLUGIN_REL;
    if !arr
        .iter()
        .any(|v| v.as_str().map(|s| s == entry).unwrap_or(false))
    {
        arr.push(json!(entry));
    }

    let mut text = serde_json::to_string_pretty(&cfg)?;
    text.push('\n');
    if path.exists() {
        let existing = std::fs::read_to_string(path)?;
        if existing == text {
            return Ok(false);
        }
    }
    std::fs::write(path, text)?;
    Ok(true)
}

fn remove_plugin_registration(path: &Path) -> Result<bool> {
    if !path.exists() {
        return Ok(false);
    }
    let text = std::fs::read_to_string(path)?;
    if text.trim().is_empty() {
        return Ok(false);
    }
    let mut cfg: Value = serde_json::from_str(&text)?;
    let Some(plugins) = cfg.get_mut("plugins") else {
        return Ok(false);
    };
    let Some(arr) = plugins.as_array_mut() else {
        return Ok(false);
    };
    let before = arr.len();
    arr.retain(|v| v.as_str().map(|s| s != PLUGIN_REL).unwrap_or(true));
    if arr.len() == before {
        return Ok(false);
    }
    if arr.is_empty() {
        cfg.as_object_mut()
            .expect("root is object")
            .remove("plugins");
    }
    let empty = cfg.as_object().map(|o| o.is_empty()).unwrap_or(false);
    if empty {
        std::fs::remove_file(path)?;
    } else {
        let mut out = serde_json::to_string_pretty(&cfg)?;
        out.push('\n');
        std::fs::write(path, out)?;
    }
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmpdir(name: &str) -> std::path::PathBuf {
        let p =
            std::env::temp_dir().join(format!("sigil_opencode_{name}_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&p);
        std::fs::create_dir_all(&p).unwrap();
        p
    }

    #[test]
    fn install_creates_all_three_artifacts() {
        let root = tmpdir("fresh");
        install(&root).unwrap();
        assert!(root.join("AGENTS.md").exists());
        assert!(root.join(PLUGIN_REL).exists());
        let cfg: Value =
            serde_json::from_str(&std::fs::read_to_string(root.join("opencode.json")).unwrap()).unwrap();
        let arr = cfg["plugins"].as_array().unwrap();
        assert!(arr.iter().any(|v| v == PLUGIN_REL));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn install_idempotent() {
        let root = tmpdir("idempotent");
        install(&root).unwrap();
        let before = std::fs::read_to_string(root.join("opencode.json")).unwrap();
        let second = install(&root).unwrap();
        let after = std::fs::read_to_string(root.join("opencode.json")).unwrap();
        assert_eq!(before, after);
        assert!(matches!(second[2], InstallStep::OpencodeJson(UpsertResult::Unchanged)));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn install_preserves_existing_opencode_json() {
        let root = tmpdir("merge");
        std::fs::write(
            root.join("opencode.json"),
            r#"{"theme": "dark", "plugins": ["plugins/user.js"]}"#,
        )
        .unwrap();
        install(&root).unwrap();
        let cfg: Value =
            serde_json::from_str(&std::fs::read_to_string(root.join("opencode.json")).unwrap()).unwrap();
        assert_eq!(cfg["theme"], "dark");
        let plugins = cfg["plugins"].as_array().unwrap();
        assert_eq!(plugins.len(), 2, "user plugin preserved + sigil added");
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn uninstall_cleans_all_artifacts() {
        let root = tmpdir("uninstall");
        install(&root).unwrap();
        uninstall(&root).unwrap();
        assert!(!root.join(PLUGIN_REL).exists());
        assert!(!root.join(".opencode/plugins").exists(), "empty plugin dir cleaned");
        assert!(!root.join("opencode.json").exists(), "empty config cleaned");
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn uninstall_preserves_user_plugin_entries() {
        let root = tmpdir("uninstall_sibling");
        std::fs::write(
            root.join("opencode.json"),
            r#"{"plugins": ["plugins/user.js"]}"#,
        )
        .unwrap();
        install(&root).unwrap();
        uninstall(&root).unwrap();
        let cfg: Value =
            serde_json::from_str(&std::fs::read_to_string(root.join("opencode.json")).unwrap()).unwrap();
        let plugins = cfg["plugins"].as_array().unwrap();
        assert_eq!(plugins.len(), 1);
        assert_eq!(plugins[0], "plugins/user.js");
        std::fs::remove_dir_all(&root).ok();
    }
}
